const { Client } = require('pg');
const fs = require('fs');

async function test() {
  const client = new Client({
    connectionString: "postgresql://postgres.rydduxnckmfpdxjinfvl:ry6oha32vwEClZ1y@57.182.231.186:5432/postgres",
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    console.log("Connected successfully to DB!");
    
    // Read the UTF-16 LE file generated by PowerShell and strip BOM
    let sql = fs.readFileSync('manual_migration.sql', 'utf16le').replace(/^\uFEFF/, '');
    
    // Some postgres syntax errors can happen with raw diffs, but this diff is simple.
    
    // Enforce gymcore schema and apply all Prisma tables
    const payload = `
      SET search_path TO gymcore;
      ${sql}
    `;
    
    await client.query(payload);
    console.log("Successfully seeded Prisma schema into gymcore!");
    
    await client.end();
  } catch (err) {
    console.error("Connection error", err.stack);
  }
}

test();
